INSERT INTO themes (name, is_active) VALUES ('Adventure', true);
INSERT INTO themes (name, is_active) VALUES ('Amusement Park (Kids)', true);
INSERT INTO themes (name, is_active) VALUES ('Art & Culture', true);
INSERT INTO themes (name, is_active) VALUES ('Beach', true);
INSERT INTO themes (name, is_active) VALUES ('Cultural Heritage', true);
INSERT INTO themes (name, is_active) VALUES ('City Exploration', true);
INSERT INTO themes (name, is_active) VALUES ('Concert', true);
INSERT INTO themes (name, is_active) VALUES ('Exhibition', true);
INSERT INTO themes (name, is_active) VALUES ('Family Friendly Spot', true);
INSERT INTO themes (name, is_active) VALUES ('Festival', true);
INSERT INTO themes (name, is_active) VALUES ('Golf Course', true);
INSERT INTO themes (name, is_active) VALUES ('Historical Sites', true);
INSERT INTO themes (name, is_active) VALUES ('Hot Springs', true);
INSERT INTO themes (name, is_active) VALUES ('Mountain', true);
INSERT INTO themes (name, is_active) VALUES ('Nature Exploration', true);
INSERT INTO themes (name, is_active) VALUES ('Natural Scenery', true);
INSERT INTO themes (name, is_active) VALUES ('Night Views', true);
INSERT INTO themes (name, is_active) VALUES ('Resort', true);
INSERT INTO themes (name, is_active) VALUES ('Sports Event', true);
INSERT INTO themes (name, is_active) VALUES ('Spa', true);
INSERT INTO themes (name, is_active) VALUES ('Water Park', true);
INSERT INTO themes (name, is_active) VALUES ('Yacht', true);
