INSERT INTO my_cards (card_id, user_id, memo, is_active) VALUES
(15, 2, 'Need to visit this place next summer', true),
(56, 1, 'Great memories from last trip', true),
(220, 3, 'Planning a business meeting here', true),
(40, 2, 'Historical landmarks to see', true),
(147, 1, 'Food recommendations needed', true),
(24, 3, 'Modern architecture tour', true),
(194, 2, 'Favorite city in the midwest', true),
(107, 1, 'Art galleries to check out', true),
(119, 3, 'Beautiful coastal views', true),
(35, 2, 'Cultural heritage sites', true),
(229, 1, 'Broadway shows to see', true),
(72, 3, 'Spicy food options', true),
(145, 2, 'Beach activities for kids', true),
(16, 1, 'Romantic dinner spots', true),
(223, 3, 'Space center tour', true),
(48, 2, 'Technology hub visit', true),
(111, 1, 'River cruise options', true),
(29, 3, 'University campus tour', true),
(195, 2, 'Historical sites checklist', true),
(43, 1, 'Shopping districts', true),
(138, 3, 'Canal tour booking', true),
(121, 2, 'Christmas market in December', true),
(33, 1, 'Tech industry connections', true),
(227, 3, 'Riverwalk restaurants', true),
(114, 2, 'Wine tasting tours', true),
(75, 1, 'Beach day planned', true),
(120, 3, 'Mediterranean cuisine', true),
(196, 2, 'BBQ restaurants to try', true),
(106, 1, 'Fashion week events', true),
(143, 3, 'Airport transportation options', true),
(221, 2, 'Desert hiking trails', true),
(13, 1, 'Must try local beers', true),
(225, 3, 'Zoo visit with family', true),
(112, 2, 'Pink city architecture', true),
(224, 1, 'Tech conference location', true),
(19, 3, 'Historical missions tour', true),
(122, 2, 'University medical center', true),
(210, 1, 'Small town version', true),
(148, 3, 'Business district hotels', true),
(12, 2, 'Traditional festivals', true),
(142, 1, 'Industrial city landmarks', true),
(175, 3, 'Local coffee recommendations', true),
(10, 2, 'Mining history tour', true),
(141, 1, 'Night markets to visit', true),
(163, 3, 'Silicon Valley companies', true),
(76, 2, 'Mountain views hiking path', true),
(140, 1, 'Traditional tea ceremony', true),
(161, 3, 'Winter Olympics venue', true),
(213, 2, 'Art festivals in February', true),
(46, 1, 'Ancient temples nearby', true),
(115, 3, 'Hillside views', true),
(53, 2, 'Local fishing spots', true),
(219, 1, 'Cowboys game tickets', true),
(102, 3, 'Coffee plantation tours', true),
(18, 2, 'Chilean wines to try', true),
(165, 1, 'Tech startups meeting', true),
(80, 3, 'Amazon rainforest tours', true),
(113, 2, 'Northern French cuisine', true),
(88, 1, 'Revolutionary war sites', true),
(205, 3, 'Suburban commuter options', true),
(97, 2, 'Car manufacturing tour', true),
(17, 1, 'Mountain biking trails', true),
(187, 3, 'Alpine skiing resort', true),
(201, 2, 'Industrial heritage museum', true),
(30, 1, 'Ancient city walls', true),
(186, 3, 'Rural countryside retreat', true),
(109, 2, 'Wine region day trip', true),
(98, 1, 'Scandinavian design shops', true),
(176, 3, 'Catholic churches tour', true),
(25, 2, 'Remote village experience', true),
(226, 1, 'NASA related activities', true),
(9, 3, 'Agricultural region products', true),
(200, 2, 'Detroit suburbs exploration', true),
(14, 1, 'Jesuit mission history', true),
(198, 3, 'Amish country nearby', true),
(108, 2, 'Atlantic coast cuisine', true),
(197, 1, 'Manhattan skyline view', true),
(8, 3, 'Buenos Aires suburb visit', true),
(151, 2, 'Hmong cultural sites', true),
(202, 1, 'Great Lakes shoreline', true),
(81, 3, 'Colombian coffee region', true),
(137, 2, 'Mayan ruins nearby', true),
(22, 1, 'Border town markets', true),
(185, 3, 'Danube river cruise', true),
(123, 2, 'Norman history sites', true),
(70, 1, 'Rural community visit', true),
(159, 3, 'Silver mining history', true),
(96, 2, 'Bohemian culture center', true),
(32, 1, 'Traditional farming methods', true),
(160, 3, 'Nicaraguan revolution sites', true),
(139, 2, 'Mediterranean beach town', true),
(45, 1, 'Ancient village structures', true),
(157, 3, 'Indigenous crafts market', true),
(36, 2, 'Grand canal bridges', true),
(124, 1, 'Pacific coast fishing', true),
(131, 3, 'Highland Maya communities', true),
(27, 2, 'Buddhist temples tour', true);